using System.Runtime.Serialization;

namespace CanardSharp.Dsdl.Testing.Serialization.AutogeneratedTests
{
    [DataContract(Name = "S00_t_uint4", Namespace = "uavcan.samples")]
    sealed class S00_t_uint4
    {
        [DataMember(Name = "val")]
        public byte val { get; set; }
    }

    [DataContract(Name = "S01_s_uint4", Namespace = "uavcan.samples")]
    sealed class S01_s_uint4
    {
        [DataMember(Name = "val")]
        public byte val { get; set; }
    }

    [DataContract(Name = "S02_uint64", Namespace = "uavcan.samples")]
    sealed class S02_uint64
    {
        [DataMember(Name = "val")]
        public ulong val { get; set; }
    }

    [DataContract(Name = "S03_int64", Namespace = "uavcan.samples")]
    sealed class S03_int64
    {
        [DataMember(Name = "val")]
        public long val { get; set; }
    }

    [DataContract(Name = "S04_bool", Namespace = "uavcan.samples")]
    sealed class S04_bool
    {
        [DataMember(Name = "val")]
        public bool val { get; set; }
    }

    [DataContract(Name = "S05_float16", Namespace = "uavcan.samples")]
    sealed class S05_float16
    {
        [DataMember(Name = "val")]
        public float val { get; set; }
    }

    [DataContract(Name = "S06_float64", Namespace = "uavcan.samples")]
    sealed class S06_float64
    {
        [DataMember(Name = "val")]
        public double val { get; set; }
    }

    [DataContract(Name = "S07_as4_uint8", Namespace = "uavcan.samples")]
    sealed class S07_as4_uint8
    {
        [DataMember(Name = "val")]
        public byte[] val { get; set; }
    }

    [DataContract(Name = "S08_ad4_uint8", Namespace = "uavcan.samples")]
    sealed class S08_ad4_uint8
    {
        [DataMember(Name = "val")]
        public byte[] val { get; set; }
    }

    [DataContract(Name = "S09_as4_uint8_ad4_uint8", Namespace = "uavcan.samples")]
    sealed class S09_as4_uint8_ad4_uint8
    {
        [DataMember(Name = "val0")]
        public byte[] val0 { get; set; }
        [DataMember(Name = "val1")]
        public byte[] val1 { get; set; }
    }

    [DataContract(Name = "S10_ad4_uint8_as4_uint8", Namespace = "uavcan.samples")]
    sealed class S10_ad4_uint8_as4_uint8
    {
        [DataMember(Name = "val0")]
        public byte[] val0 { get; set; }
        [DataMember(Name = "val1")]
        public byte[] val1 { get; set; }
    }

    [DataContract(Name = "S11_s_int24", Namespace = "uavcan.samples")]
    sealed class S11_s_int24
    {
        [DataMember(Name = "val")]
        public int val { get; set; }
    }

    [DataContract(Name = "CmpTestA", Namespace = "uavcan.samples")]
    sealed class CmpTestA
    {
        [DataMember(Name = "field")]
        public sbyte field { get; set; }
    }

    [DataContract(Name = "CmpTestA_A", Namespace = "uavcan.samples")]
    sealed class CmpTestA_A
    {
        [DataMember(Name = "field")]
        public sbyte field { get; set; }
        [DataMember(Name = "a")]
        public CmpTestA a { get; set; }
    }

}
