using System.Runtime.Serialization;

namespace Uavcan.NET.Dsdl.Testing.Serialization.AutogeneratedTests
{
    [DataContract(Name = "S00_t_uint4", Namespace = "uavcan.samples")]
    sealed class S00_t_uint4
    {
        [DataMember(Name = "val")]
        public byte val { get; set; }
    }

    [DataContract(Name = "S01_s_uint4", Namespace = "uavcan.samples")]
    sealed class S01_s_uint4
    {
        [DataMember(Name = "val")]
        public byte val { get; set; }
    }

    [DataContract(Name = "S02_uint64", Namespace = "uavcan.samples")]
    sealed class S02_uint64
    {
        [DataMember(Name = "val")]
        public ulong val { get; set; }
    }

    [DataContract(Name = "S03_int64", Namespace = "uavcan.samples")]
    sealed class S03_int64
    {
        [DataMember(Name = "val")]
        public long val { get; set; }
    }

    [DataContract(Name = "S04_bool", Namespace = "uavcan.samples")]
    sealed class S04_bool
    {
        [DataMember(Name = "val")]
        public bool val { get; set; }
    }

    [DataContract(Name = "S05_float16", Namespace = "uavcan.samples")]
    sealed class S05_float16
    {
        [DataMember(Name = "val")]
        public float val { get; set; }
    }

    [DataContract(Name = "S06_float64", Namespace = "uavcan.samples")]
    sealed class S06_float64
    {
        [DataMember(Name = "val")]
        public double val { get; set; }
    }

    [DataContract(Name = "S07_as4_uint8", Namespace = "uavcan.samples")]
    sealed class S07_as4_uint8
    {
        [DataMember(Name = "val")]
        public byte[] val { get; set; }
    }

    [DataContract(Name = "S08_ad4_uint8", Namespace = "uavcan.samples")]
    sealed class S08_ad4_uint8
    {
        [DataMember(Name = "val")]
        public byte[] val { get; set; }
    }

    [DataContract(Name = "S09_as4_uint8_ad4_uint8", Namespace = "uavcan.samples")]
    sealed class S09_as4_uint8_ad4_uint8
    {
        [DataMember(Name = "val0")]
        public byte[] val0 { get; set; }
        [DataMember(Name = "val1")]
        public byte[] val1 { get; set; }
    }

    [DataContract(Name = "S10_ad4_uint8_as4_uint8", Namespace = "uavcan.samples")]
    sealed class S10_ad4_uint8_as4_uint8
    {
        [DataMember(Name = "val0")]
        public byte[] val0 { get; set; }
        [DataMember(Name = "val1")]
        public byte[] val1 { get; set; }
    }

    [DataContract(Name = "S11_s_int24", Namespace = "uavcan.samples")]
    sealed class S11_s_int24
    {
        [DataMember(Name = "val")]
        public int val { get; set; }
    }

    [DataContract(Name = "S12_s_uint24", Namespace = "uavcan.samples")]
    sealed class S12_s_uint24
    {
        [DataMember(Name = "val")]
        public uint val { get; set; }
    }

    [DataContract(Name = "S14_s_uint24", Namespace = "uavcan.samples")]
    sealed class S14_s_uint24
    {
        [DataMember(Name = "val")]
        public uint val { get; set; }
    }

    [DataContract(Name = "CmpTestA", Namespace = "uavcan.samples")]
    sealed class CmpTestA
    {
        [DataMember(Name = "field")]
        public sbyte field { get; set; }
    }

    [DataContract(Name = "CmpTestA_A", Namespace = "uavcan.samples")]
    sealed class CmpTestA_A
    {
        [DataMember(Name = "field")]
        public sbyte field { get; set; }
        [DataMember(Name = "a")]
        public CmpTestA a { get; set; }
    }

    [DataContract(Name = "TAO1", Namespace = "uavcan.samples")]
    sealed class TAO1
    {
        [DataMember(Name = "foo")]
        public byte foo { get; set; }
        [DataMember(Name = "array")]
        public byte[] array { get; set; }
    }

    [DataContract(Name = "TAO2", Namespace = "uavcan.samples")]
    sealed class TAO2
    {
        [DataMember(Name = "foo")]
        public float foo { get; set; }
        [DataMember(Name = "array")]
        public byte[] array { get; set; }
    }

    [DataContract(Name = "TAO3", Namespace = "uavcan.samples")]
    sealed class TAO3
    {
        [DataMember(Name = "array")]
        public byte[] array { get; set; }
        [DataMember(Name = "bar")]
        public float bar { get; set; }
    }

    [DataContract(Name = "TAO4", Namespace = "uavcan.samples")]
    sealed class TAO4
    {
        [DataMember(Name = "array")]
        public bool[] array { get; set; }
    }

    [DataContract(Name = "TAO5", Namespace = "uavcan.samples")]
    sealed class TAO5
    {
        [DataMember(Name = "array")]
        public TAO4[] array { get; set; }
    }

    [DataContract(Name = "TAO6", Namespace = "uavcan.samples")]
    sealed class TAO6
    {
        [DataMember(Name = "array")]
        public TAO1[] array { get; set; }
    }

    [DataContract(Name = "TAO7", Namespace = "uavcan.samples")]
    sealed class TAO7
    {
        [DataMember(Name = "array")]
        public TAO1[] array { get; set; }
        [DataMember(Name = "baz")]
        public float baz { get; set; }
    }

    [DataContract(Name = "TAO8", Namespace = "uavcan.samples")]
    sealed class TAO8
    {
        [DataMember(Name = "fooz")]
        public sbyte fooz { get; set; }
        [DataMember(Name = "array")]
        public double[] array { get; set; }
    }

    [DataContract(Name = "TAO9", Namespace = "uavcan.samples")]
    sealed class TAO9
    {
        [DataMember(Name = "array")]
        public TAO8[] array { get; set; }
    }

    [DataContract(Name = "Union1", Namespace = "uavcan.samples")]
    sealed class Union1
    {
        [DataMember(Name = "a")]
        public ushort? a { get; set; }
        [DataMember(Name = "b")]
        public byte? b { get; set; }
        [DataMember(Name = "c")]
        public double? c { get; set; }
    }

    [DataContract(Name = "Void1", Namespace = "uavcan.samples")]
    sealed class Void1
    {
        [DataMember(Name = "i")]
        public sbyte i { get; set; }
    }

    [DataContract(Name = "Empty", Namespace = "uavcan.samples.getsettest")]
    sealed class Empty
    {
    }

    [DataContract(Name = "NumericValue", Namespace = "uavcan.samples.getsettest")]
    sealed class NumericValue
    {
        [DataMember(Name = "empty")]
        public Empty empty { get; set; }
        [DataMember(Name = "integer_value")]
        public long? integer_value { get; set; }
        [DataMember(Name = "real_value")]
        public float? real_value { get; set; }
    }

    [DataContract(Name = "Value", Namespace = "uavcan.samples.getsettest")]
    sealed class Value
    {
        [DataMember(Name = "empty")]
        public Empty empty { get; set; }
        [DataMember(Name = "integer_value")]
        public long? integer_value { get; set; }
        [DataMember(Name = "real_value")]
        public float? real_value { get; set; }
        [DataMember(Name = "boolean_value")]
        public byte? boolean_value { get; set; }
        [DataMember(Name = "string_value")]
        public byte[] string_value { get; set; }
    }

    [DataContract(Name = "GetSet", Namespace = "uavcan.samples.getsettest")]
    sealed class GetSet
    {
        [DataMember(Name = "value")]
        public Value value { get; set; }
        [DataMember(Name = "max_value")]
        public NumericValue max_value { get; set; }
        [DataMember(Name = "name")]
        public byte[] name { get; set; }
    }

    [DataContract(Name = "EnumTest", Namespace = "uavcan.samples")]
    sealed class EnumTest
    {
        [DataMember(Name = "t_enum_value")]
        public Enum_byte t_enum_value { get; set; }
    }

    [DataContract(Name = "StringTest", Namespace = "uavcan.samples")]
    sealed class StringTest
    {
        [DataMember(Name = "t_string_value")]
        public string t_string_value { get; set; }
    }

    public enum Enum_byte : byte {}
}
